services:
  registry:
    rpcEndpoint: 'http://159.203.31.82:26657'
    gqlEndpoint: 'http://159.203.31.82:9473/api'
    chainId: ${CERC_REGISTRY_CHAIN_ID:-laconic_9000-1}
    gas: 200000
    fees: 200000photon
