services:
  registry:
    rpcEndpoint: 'http://devnet.lc.stg.earthball.xyz:26657'
    gqlEndpoint: 'http://devnet.lc.stg.earthball.xyz:9473/api'
    chainId: ${CERC_REGISTRY_CHAIN_ID:-lorotestnet-1}
    gas: 200000
    fees: 200000alnt
